'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, BarChart3, LayoutDashboard, LogOut, Menu, Plus, Settings, Target, Trash2, WalletCards, X, Pencil, Check } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Transaction = { id: string; merchant: string; category: string; amount: number; transaction_type: 'income' | 'expense'; transaction_date: string }
type Account = { id: string; name: string; type: string; balance: number; currency: string }
type Budget = { id: string; category: string; limit_amount: number; spent_amount: number; month_start: string }
type Modal = 'transaction' | 'account' | 'budget' | null
const tabs = ['Overview', 'Transactions', 'Budgets', 'Accounts', 'Settings']
const categories = ['Housing', 'Food', 'Transport', 'Shopping', 'Entertainment', 'Health', 'Salary', 'Other']

export default function Page() {
  const supabase = createClient()
  const [user, setUser] = useState<any>(null); const [active, setActive] = useState('Overview'); const [menu, setMenu] = useState(false); const [signup, setSignup] = useState(false); const [authError, setAuthError] = useState('')
  const [transactions, setTransactions] = useState<Transaction[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [budgets, setBudgets] = useState<Budget[]>([]); const [modal, setModal] = useState<Modal>(null); const [editing, setEditing] = useState<any>(null); const [form, setForm] = useState<any>({ merchant: '', category: 'Food', amount: '', type: 'expense', name: '', accountType: 'checking', limit: '' }); const [saving, setSaving] = useState(false)

  useEffect(() => { supabase.auth.getUser().then(({ data }) => setUser(data.user)); const { data } = supabase.auth.onAuthStateChange((_event, session) => setUser(session?.user ?? null)); return () => data.subscription.unsubscribe() }, [supabase])
  useEffect(() => { if (user) loadAll() }, [user])
  async function loadAll() { const [t, a, b] = await Promise.all([supabase.from('transactions').select('id,merchant,category,amount,transaction_type,transaction_date').order('transaction_date', { ascending: false }), supabase.from('accounts').select('id,name,type,balance,currency').order('created_at'), supabase.from('budgets').select('id,category,limit_amount,spent_amount,month_start').order('created_at')]); setTransactions(t.data || []); setAccounts(a.data || []); setBudgets(b.data || []) }
  async function authenticate(e: React.FormEvent) { e.preventDefault(); setAuthError(''); const email = form.email.trim().toLowerCase(); let result: any; if (signup) { const response = await fetch('/api/auth/signup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password: form.password }) }); const body = await response.json(); if (!response.ok) { setAuthError(body.error || 'Unable to create account.'); return } result = await supabase.auth.signInWithPassword({ email, password: form.password }) } else result = await supabase.auth.signInWithPassword({ email, password: form.password }); if (result.error) setAuthError(result.error.message.toLowerCase().includes('invalid') ? 'Invalid email or password.' : result.error.message) }
  function openModal(kind: Modal, item?: any) { setEditing(item || null); setForm(item ? (kind === 'transaction' ? { merchant: item.merchant, category: item.category, amount: item.amount, type: item.transaction_type } : kind === 'account' ? { name: item.name, accountType: item.type, balance: item.balance } : { category: item.category, limit: item.limit_amount }) : { merchant: '', category: 'Food', amount: '', type: 'expense', name: '', accountType: 'checking', balance: '', limit: '' }); setModal(kind) }
  async function save(e: React.FormEvent) { e.preventDefault(); setSaving(true); let result: any; if (modal === 'transaction') { const payload = { merchant: form.merchant, category: form.category, amount: Number(form.amount), transaction_type: form.type, transaction_date: new Date().toISOString().slice(0, 10), user_id: user.id }; result = editing ? await supabase.from('transactions').update(payload).eq('id', editing.id) : await supabase.from('transactions').insert(payload) } else if (modal === 'account') { const payload = { name: form.name, type: form.accountType, balance: Number(form.balance || 0), currency: 'USD', user_id: user.id }; result = editing ? await supabase.from('accounts').update(payload).eq('id', editing.id) : await supabase.from('accounts').insert(payload) } else if (modal === 'budget') { const payload = { category: form.category, limit_amount: Number(form.limit), user_id: user.id }; result = editing ? await supabase.from('budgets').update(payload).eq('id', editing.id) : await supabase.from('budgets').insert(payload) } setSaving(false); if (!result?.error) { setModal(null); await loadAll() } }
  async function remove(table: string, id: string) { if (!window.confirm('Delete this item? This action cannot be undone.')) return; await supabase.from(table).delete().eq('id', id); await loadAll() }
  const income = useMemo(() => transactions.filter(t => t.transaction_type === 'income').reduce((s, t) => s + Number(t.amount), 0), [transactions]); const spending = useMemo(() => transactions.filter(t => t.transaction_type === 'expense').reduce((s, t) => s + Number(t.amount), 0), [transactions]); const balance = accounts.reduce((s, a) => s + Number(a.balance), 0)
  if (!user) return <Auth signup={signup} setSignup={setSignup} error={authError} onSubmit={authenticate} form={form} setForm={setForm} />
  return <main className="finance-app"><aside className={`sidebar ${menu ? 'sidebar-open' : ''}`}><div className="brand"><span className="brand-mark"><ArrowUpRight /></span>ledgerly</div><button className="close-menu" onClick={() => setMenu(false)}><X /></button><p className="nav-label">Workspace</p><nav className="nav-list">{tabs.map((tab, i) => { const Icon = [LayoutDashboard, ArrowDownLeft, Target, WalletCards, Settings][i]; return <button key={tab} className={`nav-item ${active === tab ? 'active' : ''}`} onClick={() => { setActive(tab); setMenu(false) }}><Icon size={18} /><span>{tab}</span></button> })}</nav><div className="sidebar-bottom"><div className="upgrade-card"><BarChart3 size={18} /><strong>Build better habits</strong><p>Small steps add up to big progress.</p></div><button className="nav-item" onClick={() => supabase.auth.signOut()}><LogOut size={18} /><span>Log out</span></button><div className="profile"><div className="avatar">{user.email?.[0]?.toUpperCase()}</div><div><strong>{user.email?.split('@')[0]}</strong><span>Personal account</span></div></div></div></aside><section className="content"><header className="topbar"><button className="menu-button" onClick={() => setMenu(true)}><Menu /></button><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{active}</strong></div><div className="mini-avatar">{user.email?.[0]?.toUpperCase()}</div></header><div className="page-wrap"><div className="welcome-row"><div><p className="eyebrow">Your financial command center</p><h1>{active === 'Overview' ? 'Good morning' : active}<span className="title-dot">.</span></h1><p className="subtitle">Your money, organized and easy to understand.</p></div>{active !== 'Settings' && <button className="primary-button" onClick={() => openModal(active === 'Budgets' ? 'budget' : active === 'Accounts' ? 'account' : 'transaction')}><Plus size={17} /> Add {active === 'Budgets' ? 'budget' : active === 'Accounts' ? 'account' : 'transaction'}</button>}</div>{active === 'Overview' && <Overview balance={balance} income={income} spending={spending} transactions={transactions} budgets={budgets} onDelete={(id) => remove('transactions', id)} />}{active === 'Transactions' && <TransactionTable rows={transactions} onEdit={(x) => openModal('transaction', x)} onDelete={(id) => remove('transactions', id)} />}{active === 'Accounts' && <AccountTable rows={accounts} onEdit={(x) => openModal('account', x)} onDelete={(id) => remove('accounts', id)} />}{active === 'Budgets' && <BudgetTable rows={budgets} onEdit={(x) => openModal('budget', x)} onDelete={(id) => remove('budgets', id)} />}{active === 'Settings' && <SettingsPanel email={user.email} onLogout={() => supabase.auth.signOut()} />}</div></section>{modal && <ModalForm kind={modal} form={form} setForm={setForm} editing={editing} saving={saving} onClose={() => setModal(null)} onSubmit={save} />}</main>
}

function Auth({ signup, setSignup, error, onSubmit, form, setForm }: any) { return <main className="auth-shell"><div className="auth-card"><div className="brand"><span className="brand-mark"><ArrowUpRight /></span>ledgerly</div><div className="auth-copy"><p className="eyebrow">Private finance workspace</p><h1>{signup ? 'Start your money story.' : 'Welcome back.'}</h1><p>{signup ? 'Create your account and take control of every dollar.' : 'Your calm, clear view of money is waiting.'}</p></div><form onSubmit={onSubmit} className="auth-form"><label>Email<input type="email" required placeholder="you@example.com" name="email" value={form.email || ''} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" required minLength={6} placeholder="At least 6 characters" name="password" value={form.password || ''} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button full-width">{signup ? 'Create account' : 'Log in'} <ArrowUpRight size={16} /></button></form><button className="auth-switch" onClick={() => setSignup(!signup)}>{signup ? 'Already have an account? Log in' : 'New here? Create an account'}</button></div><div className="auth-visual"><span className="orb" /><p>“The best financial system is the one you can actually understand.”</p><strong>Simple by design.</strong></div></main> }
function Overview({ balance, income, spending, transactions, budgets, onDelete }: any) { return <><div className="stats-grid"><div className="stat-card balance-card"><div className="card-top">Total balance <WalletCards size={17} /></div><div className="balance">${balance.toLocaleString('en-US', { minimumFractionDigits: 2 })}</div><div className="stat-trend positive"><Check size={12} /> Accounts synced</div></div><div className="stat-card"><div className="card-top">Income <ArrowDownLeft className="positive" size={17} /></div><div className="stat-number">${income.toLocaleString('en-US', { minimumFractionDigits: 2 })}</div><div className="stat-trend positive">This period</div></div><div className="stat-card"><div className="card-top">Spending <ArrowUpRight className="negative" size={17} /></div><div className="stat-number">${spending.toLocaleString('en-US', { minimumFractionDigits: 2 })}</div><div className="stat-trend negative">This period</div></div></div><section className="panel"><div className="panel-heading"><div><h2>Recent transactions</h2><p>Your latest money movement.</p></div></div><TransactionTable rows={transactions.slice(0, 5)} onDelete={onDelete} /></section><section className="panel"><div className="panel-heading"><div><h2>Budget progress</h2><p>Keep your monthly goals on track.</p></div></div><BudgetRows rows={budgets} /></section></> }
function TransactionTable({ rows, onEdit, onDelete }: any) { return <div className="table-wrap"><table><thead><tr><th>Transaction</th><th>Category</th><th>Date</th><th>Amount</th><th>Actions</th></tr></thead><tbody>{rows.length ? rows.map((t: Transaction) => <tr key={t.id}><td><strong>{t.merchant}</strong></td><td><span className="category-chip">{t.category}</span></td><td className="date-cell">{t.transaction_date}</td><td className={`amount ${t.transaction_type === 'income' ? 'income' : ''}`}>{t.transaction_type === 'income' ? '+' : '-'}${Number(t.amount).toFixed(2)}</td><td className="row-actions">{onEdit && <button className="icon-button" onClick={() => onEdit(t)} aria-label="Edit"><Pencil size={15} /></button>}<button className="icon-button danger" onClick={() => onDelete(t.id)} aria-label="Delete"><Trash2 size={15} /></button></td></tr>) : <tr><td colSpan={5} className="empty-cell">No records yet. Add your first one.</td></tr>}</tbody></table></div> }
function AccountTable({ rows, onEdit, onDelete }: any) { return <section className="panel"><div className="panel-heading"><div><h2>Your accounts</h2><p>Track balances across every account.</p></div></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Balance</th><th>Actions</th></tr></thead><tbody>{rows.length ? rows.map((a: Account) => <tr key={a.id}><td><strong>{a.name}</strong></td><td><span className="category-chip">{a.type}</span></td><td className="amount">${Number(a.balance).toFixed(2)}</td><td className="row-actions"><button className="icon-button" onClick={() => onEdit(a)}><Pencil size={15} /></button><button className="icon-button danger" onClick={() => onDelete(a.id)}><Trash2 size={15} /></button></td></tr>) : <tr><td colSpan={4} className="empty-cell">No accounts yet. Add a checking, savings, cash, or investment account.</td></tr>}</tbody></table></div></section> }
function BudgetTable({ rows, onEdit, onDelete }: any) { return <section className="panel"><div className="panel-heading"><div><h2>Monthly budgets</h2><p>Set limits and stay ahead of spending.</p></div></div><BudgetRows rows={rows} actions onEdit={onEdit} onDelete={onDelete} /></section> }
function BudgetRows({ rows, actions, onEdit, onDelete }: any) { return <div className="budget-list">{rows.length ? rows.map((b: Budget) => { const percent = Math.min(100, Number(b.spent_amount) / Number(b.limit_amount || 1) * 100); return <div className="budget-row" key={b.id}><div className="budget-meta"><span className="budget-name"><i />{b.category}</span><em>${Number(b.spent_amount).toFixed(0)} / ${Number(b.limit_amount).toFixed(0)}</em></div><div className="progress-track"><span style={{ width: `${percent}%`, background: percent > 90 ? '#ef756d' : '#25c79a' }} /></div>{actions && <div className="row-actions budget-actions"><button className="icon-button" onClick={() => onEdit(b)}><Pencil size={15} /></button><button className="icon-button danger" onClick={() => onDelete(b.id)}><Trash2 size={15} /></button></div>}</div> }) : <div className="empty-cell">No budgets yet. Add your first monthly limit.</div>}</div> }
function SettingsPanel({ email, onLogout }: any) { return <section className="panel settings-panel"><h2>Settings</h2><p>Manage your personal finance workspace.</p><label>Account email<input value={email} readOnly /></label><label>Currency<select defaultValue="USD"><option>USD — US Dollar</option></select></label><button className="outline-button" onClick={onLogout}>Log out securely</button></section> }
function ModalForm({ kind, form, setForm, editing, saving, onClose, onSubmit }: any) { const title = kind === 'transaction' ? 'transaction' : kind === 'account' ? 'account' : 'budget'; return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={onSubmit}><div className="modal-header"><div><p className="eyebrow">Ledgerly</p><h2>{editing ? 'Edit' : 'Add'} {title}</h2></div><button type="button" className="icon-button" onClick={onClose}><X /></button></div>{kind === 'transaction' && <><label>Merchant<input required value={form.merchant} onChange={e => setForm({ ...form, merchant: e.target.value })} /></label><div className="form-row"><label>Amount<input required min="0.01" step="0.01" type="number" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} /></label><label>Type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="expense">Expense</option><option value="income">Income</option></select></label></div><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{categories.map(c => <option key={c}>{c}</option>)}</select></label></>}{kind === 'account' && <><label>Account name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Main checking" /></label><div className="form-row"><label>Type<select value={form.accountType} onChange={e => setForm({ ...form, accountType: e.target.value })}><option>checking</option><option>savings</option><option>cash</option><option>investment</option><option>credit</option></select></label><label>Balance<input required type="number" step="0.01" value={form.balance || ''} onChange={e => setForm({ ...form, balance: e.target.value })} /></label></div></>}{kind === 'budget' && <><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{categories.filter(c => c !== 'Salary').map(c => <option key={c}>{c}</option>)}</select></label><label>Monthly limit<input required min="0" type="number" step="0.01" value={form.limit} onChange={e => setForm({ ...form, limit: e.target.value })} /></label></>}<button className="primary-button full-width" disabled={saving}>{saving ? 'Saving...' : editing ? 'Save changes' : `Add ${title}`} <Check size={16} /></button></form></div> }


